# Use the latest version of Ubuntu
FROM ubuntu:latest

# Update and upgrade the system
RUN apt-get update && apt-get upgrade -y

# Define the command that will be executed when the Docker container starts
CMD echo "Hello, World!"
